### ISSUE TITLE
DM does not open on my Mac Ventura 13.6

### ISSUE THREAD

**Issue by Trondtr** [divvun/divvun-manager-macos#47] opened 2023-11-01 09:11 UTC
Despite repeated reinstallations of DM and an otherwise good internet connection, I am met with this screen (which stays permanently spinning):

![kuva](https://github.com/divvun/divvun-manager-macos/assets/11891083/22bf5449-1d8a-4fd4-92a1-b08309bdc1d8)

**Comment by snomos** [comment] 2024-01-08 11:23
App log from original poster:

```log
2024-01-07 19:43:03.168 [Info] > Divvun Manager Version: 2.2.0 Build: 3 PID: 4459
2024-01-07 19:43:03.168 [Info] > XCGLogger Version: 7.0.1 - Level: Debug
2024-01-07 19:43:03.168 [Info] > XCGLogger writing log to: file:///Users/ttr000/Library/Logs/Divvun%20Manager/app.log
2024-01-07 19:43:03.173 [Debug] [App.swift:129] init() > Setting default language: nil
2024-01-07 19:43:03.329 [Debug] [RPCService.swift:498] connectivityStateDidChange(from:to:) > RPC changed state: idle -> connecting
2024-01-07 19:43:03.333 [Debug] [RPCService.swift:498] connectivityStateDidChange(from:to:) > RPC changed state: connecting -> ready
2024-01-07 19:43:03.381 [Debug] [AppDelegate.swift:22] launchMain() > Setting event handler for core open event
2024-01-07 19:43:03.528 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:03.529 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:03.543 [Debug] [MainWindow.swift:62] startRouting() > Setting route to: landing
2024-01-07 19:43:03.550 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:03.550 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:03.692 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:03.718 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:03.737 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:03.738 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:03.738 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:03.799 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:03.799 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:03.799 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:03.801 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:03.801 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:03.838 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:03.838 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:03.838 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:03.891 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:03.892 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:03.892 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:03.894 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:03.894 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:03.911 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:03.917 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:03.918 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:03.918 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:03.959 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:03.960 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:03.960 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:03.962 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:03.962 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:03.972 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:03.983 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:03.983 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:03.983 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:04.014 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.023 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:04.024 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:04.024 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:04.026 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:04.027 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:04.045 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:04.046 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:04.046 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:04.046 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.090 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.095 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:04.095 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:04.095 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:04.103 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:04.103 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:04.115 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.136 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:04.136 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:04.136 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:04.149 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.193 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.195 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:04.196 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:04.196 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:04.202 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:04.229 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:04.237 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.238 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:04.238 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:04.238 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:04.274 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:04.295 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:04.295 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:04.295 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:04.299 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:04.324 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:04.324 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:04.325 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:04.366 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:04.367 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:04.367 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:04.370 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:04.370 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:05.661 [Debug] [RPCService.swift:240] status(packageKey:target:) > Success: URL: https://pahkat.uit.no/tools/, id: macdivvun, params: nil 1
2024-01-07 19:43:05.661 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:05.661 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:05.662 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:05.662 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:05.662 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:05.662 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:05.663 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:05.663 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:05.663 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:05.664 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:05.727 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:05.727 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:05.727 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:05.762 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:05.763 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:05.797 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:05.797 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:05.797 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:05.850 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:05.851 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:05.851 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:05.859 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:06.015 [Debug] [RPCService.swift:240] status(packageKey:target:) > Success: URL: https://pahkat.uit.no/tools/, id: macdivvun, params: nil 1
2024-01-07 19:43:06.015 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
2024-01-07 19:43:06.039 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: Optional(DivvunManager.LoadedRepository)
2024-01-07 19:43:06.039 [Debug] [LandingViewController.swift:140] showNoLandingPage() > No landing page
2024-01-07 19:43:06.039 [Debug] [MainViewController.swift:9] init() > MAIN INIT
2024-01-07 19:43:06.039 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:06.040 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:06.040 [Info] [AppDelegate.swift:47] applicationDidFinishLaunching(_:) > Repository data has changed on the RPC.
2024-01-07 19:43:06.100 [Debug] [MainViewController.swift:266] viewDidDisappear() > CLEARING MAIN BAG
2024-01-07 19:43:06.100 [Debug] [LandingViewController.swift:181] bindRepoDropdown() > Dropdown changed: nil
2024-01-07 19:43:06.100 [Debug] [LandingViewController.swift:133] showNoSelection() > No selection
2024-01-07 19:43:06.103 [Debug] [MainViewController.swift:35] deinit > MAIN DEINIT
2024-01-07 19:43:06.104 [Debug] [MainPresenter.swift:348] deinit > MainPresenter DEINIT
```

**Comment by dylanhand** [comment] 2024-05-07 14:19
This looks like a duplicate of #41.

If you agree @snomos I'll mark it as such and close.

**Comment by snomos** [comment] 2024-05-07 14:22
I agree.

**Comment by dylanhand** [comment] 2024-05-07 14:24
Duplicate of #41.

**Closed by dylanhand** 2024-05-07 14:24 UTC
Labels: bug, duplicate
